### ISSUE TITLE
Support for Guid-types

### ISSUE THREAD

**Issue by enkelmedia** [pankleks/TypeScriptBuilder#24]
Hi!

A guid-property on a class generates some static class that does not compile as TypeScript.

```
namespace System
{
    export interface IGuid
    {
        static readonly empty: IGuid;
    }
}
```

I tend to use string as the TypeScript type for Guids. 

Is this repo actively maintained, I would be open to create a PR if you still merge them?

**Comment by pankleks** [comment]
please feel free to create PR :)

**Comment by enkelmedia** [comment]
Fixed in PR: https://github.com/pankleks/TypeScriptBuilder/pull/26
